### ISSUE TITLE
After logging in, all pages redirect to /profiles/create with HTTP error 500

### ISSUE THREAD

**Issue by PJM257** [404talentnotfound/Glomble#3]
After logging in to the site and the "sessionid" cookie is created, attempting to view any page on the domain redirects without console feedback to /profiles/create, and returns an error 500. Clearing the sessionid cookie fixes the issue, but unable to login. No other errors or feedback in the console.

**Comment by 404talentnotfound** [comment]
I will attempt to fix this tomorrow, it's 1 am here though so I really do
need to sleep. The redirection is on purpose but is the 500 error occurring
before or after submitting a profile?

**Comment by PJM257** [comment]
The 500 error occurs after logging in.

**Comment by 404talentnotfound** [comment]
fixed, the navbar was trying to find the user's profile before it being created.
